In [313]:
#Imports
import numpy as np

In [314]:
# 1. Знайти в датасеті таргет. Завантажити датасет без таргета

source_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.loadtxt(source_url, delimiter = ',', usecols=(0,1,2,3), dtype=float)

In [315]:
# 2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)
print(f"Data ndim = {data.ndim}")
print(f"Data shape = {data.shape}")
print(f"Data sample = {data[0]}")

Data ndim = 2
Data shape = (150, 4)
Data sample = [5.1 3.5 1.4 0.2]


In [316]:
# 3. Порахувати mean, median, standard deviation для 1-ї колонки

first_col = data[:, 0]
print(f"First column mean = {np.mean(first_col)}")
print(f"First column median = {np.median(first_col)}")
print(f"First column standard deviation = {np.std(first_col)}")

First column mean = 5.843333333333334
First column median = 5.8
First column standard deviation = 0.8253012917851409


In [317]:
# 4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

indices = np.random.choice(data.size, size=20, replace=False)
data.flat[indices] = np.nan
print(f"Data\n{data}")

Data
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 nan 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 nan]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [nan 3.4 1.9 0.2]
 [nan 3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 nan 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3

In [318]:
# 5. Знайти позиції вставлених значень np.nan в 1-й колонці

nan_positions = np.where(np.isnan(first_col))[0]
print(f"NaN rows = {nan_positions}")

NaN rows = [ 24  25  55  65  78 111 129 146]


In [319]:
# 6. Замінити всі значення np.nan на 0

data[np.isnan(data)] = 0
print(f"Data\n{data}")

Data
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 0.  1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0. ]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [0.  3.4 1.9 0.2]
 [0.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 0.  0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3

In [320]:
# 7. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

mask = (data[:, 2] > 1.5) & (data[:, 0] < 5.0)
filtered = data[mask]
print(f"Filtered data\n{filtered}")

Filtered data
[[4.8 3.4 1.6 0.2]
 [0.  3.4 1.9 0.2]
 [0.  3.  1.6 0.2]
 [4.7 3.2 1.6 0.2]
 [0.  2.8 4.5 1.3]
 [4.9 2.4 3.3 1. ]
 [0.  3.1 4.4 1.4]
 [0.  2.9 4.5 1.5]
 [4.9 2.5 4.5 1.7]
 [0.  2.7 5.3 1.9]
 [0.  3.  5.8 1.6]
 [0.  2.5 5.  1.9]]


In [321]:
# 8. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

top, bottom = np.vsplit(data, 2)
print(f"Top data\n{top}")
print(f"Bottom data\n{bottom}")

Top data
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 0.  1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0. ]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [0.  3.4 1.9 0.2]
 [0.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 0.  0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [322]:
# 9. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

top_sorted = top[np.argsort(top[:, 0])]
print(f"Top sorted data\n{top_sorted}")
bottom_sorted = bottom[np.argsort(-bottom[:, 0])]
print(f"Bottom sorted data\n{bottom_sorted}")

Top sorted data
[[0.  2.8 4.5 1.3]
 [0.  3.4 1.9 0.2]
 [0.  3.1 4.4 1.4]
 [0.  3.  1.6 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.2 1.2 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 0. ]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 0.  1.7 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 3.5 1.3 0

In [323]:
# 10. Зібрати обидва массиви в одне ціле

data = np.vstack([top_sorted, bottom_sorted])
print(f"New data\n{data}")

New data
[[0.  2.8 4.5 1.3]
 [0.  3.4 1.9 0.2]
 [0.  3.1 4.4 1.4]
 [0.  3.  1.6 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.2 1.2 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 0. ]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 0.  1.7 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 3.5 1.3 0.2]
 [5

In [324]:
# 11. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

values, counts = np.unique(data, return_counts=True)
print(f"Unique values\n{np.column_stack((values, counts))}")

Unique values
[[ 0.  20. ]
 [ 0.1  6. ]
 [ 0.2 27. ]
 [ 0.3  7. ]
 [ 0.4  7. ]
 [ 0.5  1. ]
 [ 0.6  1. ]
 [ 1.   7. ]
 [ 1.1  4. ]
 [ 1.2  7. ]
 [ 1.3 20. ]
 [ 1.4 19. ]
 [ 1.5 24. ]
 [ 1.6 10. ]
 [ 1.7  6. ]
 [ 1.8 10. ]
 [ 1.9  7. ]
 [ 2.   7. ]
 [ 2.1  6. ]
 [ 2.2  6. ]
 [ 2.3 11. ]
 [ 2.4  6. ]
 [ 2.5 11. ]
 [ 2.6  5. ]
 [ 2.7  8. ]
 [ 2.8 14. ]
 [ 2.9 10. ]
 [ 3.  26. ]
 [ 3.1 12. ]
 [ 3.2 13. ]
 [ 3.3  8. ]
 [ 3.4 12. ]
 [ 3.5  8. ]
 [ 3.6  4. ]
 [ 3.7  4. ]
 [ 3.8  7. ]
 [ 3.9  4. ]
 [ 4.   6. ]
 [ 4.1  4. ]
 [ 4.2  5. ]
 [ 4.3  3. ]
 [ 4.4  8. ]
 [ 4.5  9. ]
 [ 4.6  7. ]
 [ 4.7  7. ]
 [ 4.8  8. ]
 [ 4.9 11. ]
 [ 5.  13. ]
 [ 5.1 17. ]
 [ 5.2  6. ]
 [ 5.3  3. ]
 [ 5.4  8. ]
 [ 5.5 10. ]
 [ 5.6 12. ]
 [ 5.7 10. ]
 [ 5.8 10. ]
 [ 5.9  5. ]
 [ 6.   7. ]
 [ 6.1  9. ]
 [ 6.2  4. ]
 [ 6.3  9. ]
 [ 6.4  7. ]
 [ 6.5  5. ]
 [ 6.6  3. ]
 [ 6.7  9. ]
 [ 6.8  3. ]
 [ 6.9  5. ]
 [ 7.   1. ]
 [ 7.1  1. ]
 [ 7.2  2. ]
 [ 7.3  1. ]
 [ 7.4  1. ]
 [ 7.6  1. ]
 [ 7.7  4. ]
 [ 7.9  1. ]]


In [325]:
# 12. Знайти найбільш часто повторюване значення в массиві

most_common = values[np.argmax(counts)]
print(f"Most common value = {most_common}")

Most common value = 0.2


In [326]:
# 13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

def transform_column(col):
    mean = col.mean()
    return np.where(col < mean, col * 2, col / 4)

In [327]:
# 14. Застосувати отриману функцію до 3-ї колонки. Функція має прийняти лише одну колонку і повернути колонку із зміненими значеннями

col3_mean = data[:, 2].mean()
print(f"Column 3 mean = {col3_mean}")
data[:, 2] = transform_column(data[:, 2])
print(f"Transformed data\n{data}")

Column 3 mean = 3.748
Transformed data
[[0.    2.8   1.125 1.3  ]
 [0.    3.4   3.8   0.2  ]
 [0.    3.1   1.1   1.4  ]
 [0.    3.    3.2   0.2  ]
 [4.3   3.    2.2   0.1  ]
 [4.4   3.    2.6   0.2  ]
 [4.4   3.2   2.6   0.2  ]
 [4.4   2.9   2.8   0.2  ]
 [4.5   2.3   2.6   0.3  ]
 [4.6   3.2   2.8   0.2  ]
 [4.6   3.4   2.8   0.3  ]
 [4.6   3.1   3.    0.2  ]
 [4.6   3.6   2.    0.2  ]
 [4.7   3.2   3.2   0.2  ]
 [4.7   3.2   2.6   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.8   3.    2.8   0.1  ]
 [4.8   3.1   0.    0.2  ]
 [4.8   3.    2.8   0.3  ]
 [4.9   3.1   3.    0.1  ]
 [4.9   2.4   6.6   1.   ]
 [4.9   3.1   3.    0.1  ]
 [4.9   3.    2.8   0.2  ]
 [4.9   3.1   3.    0.1  ]
 [5.    3.5   3.2   0.6  ]
 [5.    3.2   2.4   0.2  ]
 [5.    3.3   2.8   0.2  ]
 [5.    2.    7.    0.   ]
 [5.    3.4   3.2   0.4  ]
 [5.    3.5   2.6   0.3  ]
 [5.    3.4   3.    0.2  ]
 [5.    3.6   2.8   0.2  ]
 [5.1   3.8   3.8   0.4  ]
 [5.1   3.4   3.    0.2  ]
 [5.1   3.8   3.2   0.2  ]
 [5.1   3.5   2.